"""Robust clutter / unknown-noise primitives for DP-based MTT."""

from .clutter import GridClutterIntensity, UniformClutterIntensity
from .confirmation import (
    CandidateBirth,
    ConfirmationDecision,
    estimate_bayesian_fdr,
    posterior_existence_from_log_bayes_factor,
    select_by_bayesian_fdr,
)
from .dp_clutter import DPGaussianComponent, OnlineDPGaussianClutterIntensity
from .experiment import (
    ExperimentConfig,
    MethodResult,
    build_clutter_model,
    run_method,
    run_structured_clutter_comparison,
)
from .metrics import (
    ConfirmationMetrics,
    ConfirmationRecord,
    GospaDecomposition,
    GospaMatch,
    PointObject,
    confirmation_metrics,
    gospa_decomposition,
)
from .scoring import (
    AssociationResult,
    BirthModel,
    MeasurementModel,
    TrackPrediction,
    compete_measurement,
    gaussian_logpdf,
    student_t_logpdf,
)
from .simulation import (
    ClutterHotspot,
    LinearTarget,
    SimulatedMeasurement,
    SimulatedTruth,
    SimulationConfig,
    SimulationFrame,
    SimulationRun,
    StructuredClutterIntensity,
    simulate_structured_clutter_scene,
)
from .tracklet import (
    TentativeBirthManager,
    TentativeTracklet,
    TrackletManagerConfig,
    TrackletStepSummary,
    birth_vs_clutter_log_bayes_factor,
    tracklet_truth_labels,
)

__all__ = [
    "AssociationResult",
    "BirthModel",
    "CandidateBirth",
    "ClutterHotspot",
    "ConfirmationDecision",
    "ConfirmationMetrics",
    "ConfirmationRecord",
    "DPGaussianComponent",
    "ExperimentConfig",
    "GospaDecomposition",
    "GospaMatch",
    "GridClutterIntensity",
    "LinearTarget",
    "MeasurementModel",
    "MethodResult",
    "OnlineDPGaussianClutterIntensity",
    "PointObject",
    "SimulatedMeasurement",
    "SimulatedTruth",
    "SimulationConfig",
    "SimulationFrame",
    "SimulationRun",
    "StructuredClutterIntensity",
    "TentativeBirthManager",
    "TentativeTracklet",
    "TrackPrediction",
    "TrackletManagerConfig",
    "TrackletStepSummary",
    "UniformClutterIntensity",
    "birth_vs_clutter_log_bayes_factor",
    "build_clutter_model",
    "compete_measurement",
    "confirmation_metrics",
    "estimate_bayesian_fdr",
    "gaussian_logpdf",
    "gospa_decomposition",
    "posterior_existence_from_log_bayes_factor",
    "run_method",
    "run_structured_clutter_comparison",
    "select_by_bayesian_fdr",
    "simulate_structured_clutter_scene",
    "student_t_logpdf",
    "tracklet_truth_labels",
]
