"""Spatial clutter intensity models."""

from __future__ import annotations

from dataclasses import dataclass
from math import log
from typing import Sequence

import numpy as np
from numpy.typing import ArrayLike, NDArray


@dataclass(frozen=True)
class UniformClutterIntensity:
    """Uniform clutter intensity over a finite measurement volume.

    Parameters
    ----------
    rate:
        Expected clutter count per scan.
    volume:
        Volume/area/length of the surveillance region in measurement space.
    """

    rate: float
    volume: float

    def __post_init__(self) -> None:
        if self.rate < 0:
            raise ValueError("rate must be non-negative")
        if self.volume <= 0:
            raise ValueError("volume must be positive")

    def log_intensity(self, measurement: ArrayLike) -> float:  # noqa: ARG002 - protocol compatibility
        if self.rate == 0:
            return -np.inf
        return float(log(self.rate / self.volume))


@dataclass(frozen=True)
class GridClutterIntensity:
    """Piecewise-constant spatial clutter intensity.

    ``cell_intensities`` stores intensity values per measurement-space cell, not
    probabilities. This lets the grid compete directly against target predictive
    likelihoods in association scoring.
    """

    bounds: tuple[tuple[float, float], ...]
    cell_intensities: NDArray[np.float64]
    outside_intensity: float = 1e-12

    def __post_init__(self) -> None:
        if not self.bounds:
            raise ValueError("bounds must not be empty")
        for low, high in self.bounds:
            if not low < high:
                raise ValueError("each bound must satisfy low < high")
        if self.cell_intensities.ndim != len(self.bounds):
            raise ValueError("cell_intensities dimension must match bounds")
        if np.any(self.cell_intensities < 0):
            raise ValueError("cell intensities must be non-negative")
        if self.outside_intensity < 0:
            raise ValueError("outside_intensity must be non-negative")

    @classmethod
    def from_samples(
        cls,
        samples: ArrayLike,
        bounds: Sequence[tuple[float, float]],
        bins: Sequence[int],
        total_rate: float | None = None,
        smoothing: float = 1.0,
        outside_intensity: float = 1e-12,
    ) -> "GridClutterIntensity":
        """Estimate a grid intensity from clutter-responsibility samples.

        ``samples`` can be raw clutter-like measurements or replicated/weighted
        samples generated by a higher-level responsibility calculation. If
        ``total_rate`` is omitted, the sample count is used as the rate scale.
        """

        sample_arr = np.asarray(samples, dtype=float)
        if sample_arr.ndim != 2:
            raise ValueError("samples must be a two-dimensional array")
        if len(bounds) != sample_arr.shape[1]:
            raise ValueError("bounds dimension must match sample dimension")
        if len(bins) != sample_arr.shape[1] or any(b <= 0 for b in bins):
            raise ValueError("bins must contain one positive count per dimension")
        if smoothing < 0:
            raise ValueError("smoothing must be non-negative")
        if total_rate is None:
            total_rate = float(sample_arr.shape[0])
        if total_rate < 0:
            raise ValueError("total_rate must be non-negative")

        hist, _ = np.histogramdd(sample_arr, bins=bins, range=list(bounds))
        smoothed = hist + smoothing
        mass = smoothed / float(np.sum(smoothed))

        cell_volume = 1.0
        for (low, high), count in zip(bounds, bins, strict=True):
            cell_volume *= (high - low) / count

        intensities = total_rate * mass / cell_volume
        return cls(
            bounds=tuple((float(low), float(high)) for low, high in bounds),
            cell_intensities=np.asarray(intensities, dtype=float),
            outside_intensity=outside_intensity,
        )

    def log_intensity(self, measurement: ArrayLike) -> float:
        z = np.asarray(measurement, dtype=float)
        if z.ndim != 1 or z.size != len(self.bounds):
            raise ValueError("measurement dimension must match bounds")

        index: list[int] = []
        for value, (low, high), count in zip(z, self.bounds, self.cell_intensities.shape, strict=True):
            if value < low or value >= high:
                return -np.inf if self.outside_intensity == 0 else float(log(self.outside_intensity))
            relative = (value - low) / (high - low)
            index.append(min(int(relative * count), count - 1))

        intensity = float(self.cell_intensities[tuple(index)])
        if intensity == 0:
            return -np.inf
        return float(log(intensity))
